### ISSUE TITLE
Suggestion: Display public repo URL(s) more prominently

### ISSUE THREAD

**Issue by artystable** [atillaturkmen/youtube-rewind#3]
I came across this project's online site by cheer luck and it was very much the resource I was looking for. I didn't see any mentions of it being an open source or free software project. Also, while looking up the project name directly via GitHub search the repo didn't  come up at the top for me.

Since this project was so useful for me, I'm sure others may find it useful to know that the project's software is available for easy reviewing on GitHub. A simple navbar link URL or something like the more classic ['"Fork me on GitHub" ribbons](https://simonwhitaker.github.io/github-fork-ribbon-css/) might be useful to help other users find their way to the project repository from the site more easily.

**Comment by atillaturkmen** [comment]
Thanks for the feedback! I added a link to the repository in the navbar. Now other people can easily access our project's GitHub repository to review the code, documentation, and other resources.
